services:
  - type: web
    name: nakshatra-api
    env: python
    plan: free
    region: oregon
    pythonVersion: "3.11.6"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
